// examples/nextjs/src/app/page.tsx
'use client'

import { useState } from 'react'

export default function Home() {
  const [count, setCount] = useState(0)

  return (
    <main style={{ padding: '2rem', textAlign: 'center' }}>
      <h1>Next.js Counter</h1>
      <p>
        Count:
        {count}
      </p>
      <button type="button" onClick={() => setCount(count + 1)}>
        Increment
      </button>
    </main>
  )
}

// examples/nuxt/app.vue
<script setup lang="ts">
const count = ref(0)

function increment(): void {
  count.value++
}
</script>

<template>
  <main>
    <h1>Nuxt Counter</h1>
    <p>Count: {{ count }}</p>
    <button
      type="button"
      @click="increment"
    >
      Increment
    </button>
  </main>
</template>

<style scoped>
main {
  text-align: center;
  padding: 2rem;
}

button {
  padding: 0.5rem 1rem;
  font-size: 1rem;
  cursor: pointer;
}
</style>
