// examples/vue2/src/App.vue
<script lang="ts">
import Vue from 'vue'
import Counter from './components/Counter.vue'
import UserCard from './components/UserCard.vue'
import Tabs from './components/Tabs.vue'
import { calculateUserStats, filterUsers, mockUsers, sortUsers } from './utils/helpers'
import type { User, UserStats } from './utils/helpers'

export default Vue.extend({
  name: 'App',
  components: {
    Counter,
    UserCard,
    Tabs,
  },
  data() {
    return {
      users: [] as User[],
      loading: false,
      error: null as string | null,
      searchQuery: '',
      selectedRole: '' as User['role'] | '',
      sortBy: 'name' as keyof User,
      sortOrder: 'asc' as 'asc' | 'desc',
      selectedUser: null as User | null,
      theme: 'light' as 'light' | 'dark',
      activeTab: 'users',
    }
  },
  computed: {
    stats(): UserStats {
      return calculateUserStats(this.users)
    },
    filteredUsers(): User[] {
      let result = this.users

      // Filter by role
      if (this.selectedRole) {
        result = result.filter((user) => user.role === this.selectedRole)
      }

      // Filter by search
      result = filterUsers(result, this.searchQuery)

      // Sort
      result = sortUsers(result, this.sortBy, this.sortOrder)

      return result
    },
    tabs(): Array<{ id: string; label: string }> {
      return [
        { id: 'counter', label: 'Counter' },
        { id: 'users', label: 'Users' },
      ]
    },
  },
  mounted() {
    this.loadUsers()
  },
  methods: {
    async loadUsers(): Promise<void> {
      this.loading = true
      this.error = null

      try {
        // Simulate API call
        await new Promise((resolve) => setTimeout(resolve, 500))
        this.users = [...mockUsers]
      } catch (err) {
        this.error = err instanceof Error ? err.message : 'Failed to load users'
      } finally {
        this.loading = false
      }
    },
    toggleTheme(): void {
      this.theme = this.theme === 'light' ? 'dark' : 'light'
    },
    toggleSortOrder(): void {
      this.sortOrder = this.sortOrder === 'asc' ? 'desc' : 'asc'
    },
    selectUser(user: User | null): void {
      this.selectedUser = user
    },
    deleteUser(userId: number): void {
      this.users = this.users.filter((u) => u.id !== userId)

      if (this.selectedUser?.id === userId) {
        this.selectedUser = null
      }
    },
    handleTabChange(tabId: string): void {
      this.activeTab = tabId
    },
  },
})
</script>

<template>
  <div id="app" class="app-container" :class="[theme]">
    <header>
      <h1>Vue 2 + ESLint Sets Example</h1>
      <button
        type="button"
        @click="toggleTheme"
      >
        Toggle Theme ({{ theme }})
      </button>
    </header>

    <Tabs
      :tabs="tabs"
      default-tab="users"
      @change="handleTabChange"
    >
      <div v-if="activeTab === 'counter'">
        <Counter />
      </div>
      <div v-else-if="activeTab === 'users'">
        <!-- Stats -->
        <div class="stats">
          <h3>Statistics</h3>
          <p>Total: {{ stats.totalCount }} users</p>
          <p>Admins: {{ stats.adminCount }}</p>
          <p>Users: {{ stats.userCount }}</p>
          <p>Guests: {{ stats.guestCount }}</p>
        </div>

        <!-- Filters -->
        <div class="filters">
          <input
            v-model="searchQuery"
            type="text"
            placeholder="Search users..."
          >
          <select v-model="selectedRole">
            <option value="">
              All Roles
            </option>
            <option value="admin">
              Admin
            </option>
            <option value="user">
              User
            </option>
            <option value="guest">
              Guest
            </option>
          </select>
          <select v-model="sortBy">
            <option value="name">
              Sort by Name
            </option>
            <option value="email">
              Sort by Email
            </option>
            <option value="role">
              Sort by Role
            </option>
          </select>
          <button
            type="button"
            @click="toggleSortOrder"
          >
            {{ sortOrder === 'asc' ? '↑ Asc' : '↓ Desc' }}
          </button>
          <button
            type="button"
            @click="loadUsers"
          >
            Refresh
          </button>
        </div>

        <!-- Loading State -->
        <p
          v-if="loading"
          class="loading"
        >
          Loading users...
        </p>

        <!-- Error State -->
        <p
          v-if="error"
          class="error"
        >
          {{ error }}
        </p>

        <!-- User List -->
        <div
          v-if="!loading && !error"
          class="user-list"
        >
          <UserCard
            v-for="user in filteredUsers"
            :key="user.id"
            :user="user"
            :show-email="selectedUser?.id === user.id"
            @select="selectUser"
            @delete="deleteUser"
          />
        </div>

        <!-- Empty State -->
        <p v-if="!loading && !error && filteredUsers.length === 0">
          No users found.
        </p>

        <!-- Selected User -->
        <div
          v-if="selectedUser"
          class="selected-user"
        >
          <h3>Selected User</h3>
          <p>Name: {{ selectedUser.name }}</p>
          <p>Email: {{ selectedUser.email }}</p>
          <p>Role: {{ selectedUser.role }}</p>
          <button
            type="button"
            @click="selectUser(null)"
          >
            Clear Selection
          </button>
        </div>
      </div>
    </Tabs>
  </div>
</template>

<style>
.app-container {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
  padding: 20px;
}

.app-container.dark {
  background-color: #1a1a1a;
  color: #fff;
}

header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2rem;
}

button {
  padding: 10px 20px;
  font-size: 16px;
  cursor: pointer;
  margin: 0.25rem;
}

input,
select {
  padding: 0.5rem;
  font-size: 1rem;
  margin: 0.5rem;
}

.filters {
  margin: 1rem 0;
}

.user-list {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 1rem;
  margin-top: 1rem;
}

.loading {
  color: #666;
}

.error {
  color: red;
}

.stats {
  background: #f5f5f5;
  padding: 1rem;
  border-radius: 8px;
  margin: 1rem 0;
}

.dark .stats {
  background: #2a2a2a;
}

.selected-user {
  background: #f0f0f0;
  padding: 1rem;
  border-radius: 8px;
  margin-top: 1rem;
}

.dark .selected-user {
  background: #2a2a2a;
}
</style>

// examples/angular/src/app/app.component.ts
import type { User, UserStats } from './models/user.model'
import { AsyncPipe, CommonModule } from '@angular/common'
import { Component, computed, effect, inject, signal } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { CounterComponent } from './components/counter/counter.component'
import { UserCardComponent } from './components/user-card/user-card.component'
import { CounterService } from './services/counter.service'
import { UserService } from './services/user.service'
import { calculateUserStats, filterUsers, sortUsers } from './utils/helpers'

@Component({
  imports: [AsyncPipe, CommonModule, CounterComponent, FormsModule, UserCardComponent],
  selector: 'app-root',
  standalone: true,
  styles: `
    main {
      text-align: center;
      padding: 2rem;
      max-width: 800px;
      margin: 0 auto;
    }
    button {
      padding: 0.5rem 1rem;
      font-size: 1rem;
      cursor: pointer;
      margin: 0.25rem;
    }
    input, select {
      padding: 0.5rem;
      font-size: 1rem;
      margin: 0.5rem;
    }
    .user-list {
      display: flex;
      flex-wrap: wrap;
      justify-content: center;
      gap: 1rem;
      margin-top: 1rem;
    }
    .stats {
      background: #f5f5f5;
      padding: 1rem;
      border-radius: 8px;
      margin: 1rem 0;
    }
    .filters {
      margin: 1rem 0;
    }
    .loading {
      color: #666;
    }
    .error {
      color: red;
    }
  `,
  template: `
    <main>
      <h1>Angular + ESLint Sets Example</h1>

      <!-- Counter Section -->
      <section>
        <h2>Counter: {{ counterService.value() }}</h2>
        <button type="button" (click)="counterService.increment()">+</button>
        <button type="button" (click)="counterService.decrement()">-</button>
        <button type="button" (click)="counterService.reset()">Reset</button>
      </section>

      <!-- User Management Section -->
      <section>
        <h2>User Management</h2>

        <!-- Stats -->
        <div class="stats">
          <h3>Statistics</h3>
          <p>Total: {{ userStats().totalCount }} users</p>
          <p>Admins: {{ userStats().adminCount }}</p>
          <p>Users: {{ userStats().userCount }}</p>
          <p>Guests: {{ userStats().guestCount }}</p>
        </div>

        <!-- Filters -->
        <div class="filters">
          <input
            type="text"
            placeholder="Search users..."
            [ngModel]="searchQuery()"
            (ngModelChange)="searchQuery.set($event)"
          />
          <select [ngModel]="selectedRole()" (ngModelChange)="selectedRole.set($event)">
            <option value="">All Roles</option>
            <option value="admin">Admin</option>
            <option value="user">User</option>
            <option value="guest">Guest</option>
          </select>
          <select [ngModel]="sortBy()" (ngModelChange)="sortBy.set($event)">
            <option value="name">Sort by Name</option>
            <option value="email">Sort by Email</option>
            <option value="role">Sort by Role</option>
          </select>
        </div>

        <!-- Loading State -->
        @if (loading()) {
          <div class="loading">
            Loading users...
          </div>
        }

        <!-- Error State -->
        @if (error()) {
          <div class="error">
            {{ error() }}
          </div>
        }

        <!-- User List -->
        @if (!loading() && !error()) {
          <div class="user-list">
            @for (user of filteredUsers(); track user.id) {
              <app-user-card
                [user]="user"
                (select)="onUserSelect($event)"
                (delete)="onUserDelete($event)"
              />
            }
          </div>
        }

        <!-- Empty State -->
        @if (!loading() && !error() && filteredUsers().length === 0) {
          <div>
            No users found.
          </div>
        }
      </section>

      <!-- Selected User -->
      @if (selectedUser()) {
        <section>
          <h3>Selected User</h3>
          <p>Name: {{ selectedUser()!.name }}</p>
          <p>Email: {{ selectedUser()!.email }}</p>
          <p>Role: {{ selectedUser()!.role }}</p>
          <button type="button" (click)="selectedUser.set(null)">Clear Selection</button>
        </section>
      }
    </main>
  `,
})
export class AppComponent {
  // Services
  readonly counterService = inject(CounterService)
  private readonly userService = inject(UserService)

  constructor() {
    // Load users on init
    this.loadUsers()

    // Effect to log counter changes
    effect(() => {
      console.warn('Counter value:', this.counterService.value())
    })
  }

  // User state
  readonly users = signal<User[]>([])
  readonly loading = signal(false)
  readonly error = signal<string | null>(null)
  readonly selectedUser = signal<User | null>(null)

  // Filter state
  readonly searchQuery = signal('')
  readonly selectedRole = signal<User['role'] | ''>('')
  readonly sortBy = signal<keyof User>('name')
  readonly sortOrder = signal<'asc' | 'desc'>('asc')

  // Computed values
  readonly userStats = computed<UserStats>(() => calculateUserStats(this.users()))

  readonly filteredUsers = computed(() => {
    let result = this.users()

    // Filter by role
    const role = this.selectedRole()
    if (role) {
      result = result.filter(user => user.role === role)
    }

    // Filter by search
    result = filterUsers(result, this.searchQuery())

    // Sort
    result = sortUsers(result, this.sortBy(), this.sortOrder())

    return result
  })

  // Methods
  loadUsers(): void {
    this.loading.set(true)
    this.error.set(null)

    this.userService.getAll().subscribe({
      error: err => {
        this.error.set(err.message ?? 'Failed to load users')
        this.loading.set(false)
      },
      next: users => {
        this.users.set(users)
        this.loading.set(false)
      },
    })
  }

  onUserSelect(user: User): void {
    this.selectedUser.set(user)
  }

  onUserDelete(userId: number): void {
    this.userService.delete(userId).subscribe({
      next: success => {
        if (success) {
          this.users.update(users => users.filter(u => u.id !== userId))
          if (this.selectedUser()?.id === userId) {
            this.selectedUser.set(null)
          }
        }
      },
    })
  }
}
