// examples/nuxt/app.vue
<script setup lang="ts">
const count = ref(0)

function increment(): void {
  count.value++
}
</script>

<template>
  <main>
    <h1>Nuxt Counter</h1>
    <p>Count: {{ count }}</p>
    <button
      type="button"
      @click="increment"
    >
      Increment
    </button>
  </main>
</template>

<style scoped>
main {
  text-align: center;
  padding: 2rem;
}

button {
  padding: 0.5rem 1rem;
  font-size: 1rem;
  cursor: pointer;
}
</style>

// examples/angular/src/app/app.component.ts
import { CommonModule } from '@angular/common'
import { Component, signal } from '@angular/core'

@Component({
  imports: [CommonModule],
  selector: 'app-root',
  standalone: true,
  styles: `
    main {
      text-align: center;
      padding: 2rem;
    }
    button {
      padding: 0.5rem 1rem;
      font-size: 1rem;
      cursor: pointer;
    }
  `,
  template: `
    <main>
      <h1>Angular Counter</h1>
      <p>Count: {{ count() }}</p>
      <button (click)="increment()">Increment</button>
    </main>
  `,
})
export class AppComponent {
  count = signal(0)

  increment(): void {
    this.count.update((value) => value + 1)
  }
}
