// examples/unocss/src/components/CounterDisplay.vue
<script setup lang="ts">
import { useCounter } from '../composables/useCounter'

const props = withDefaults(
  defineProps<{
    initialValue?: number
    max?: number
    min?: number
  }>(),
  {
    initialValue: 0,
    max: 10,
    min: 0,
  },
)

const { count, increment, decrement, reset, isMin, isMax } = useCounter({
  initialValue: props.initialValue,
  max: props.max,
  min: props.min,
  step: 1,
})
</script>

<template>
  <div class="text-center p-5 border-2 border-blue-500 rounded-xl max-w-75 mx-auto my-5">
    <h2 class="text-xl font-bold mb-4">
      Counter Example
    </h2>
    <p class="text-5xl font-bold text-blue-500 mb-4">
      {{ count }}
    </p>
    <div class="flex justify-center gap-3 mb-4">
      <button
        type="button"
        class="px-6 py-3 text-lg border-none rounded-lg cursor-pointer bg-blue-500 text-white transition-colors duration-200 disabled:bg-gray-300 disabled:cursor-not-allowed hover:bg-blue-600 disabled:hover:bg-gray-300"
        :disabled="isMin"
        @click="decrement"
      >
        -
      </button>
      <button
        type="button"
        class="px-6 py-3 text-lg border-none rounded-lg cursor-pointer bg-blue-500 text-white transition-colors duration-200 hover:bg-blue-600"
        @click="reset"
      >
        Reset
      </button>
      <button
        type="button"
        class="px-6 py-3 text-lg border-none rounded-lg cursor-pointer bg-blue-500 text-white transition-colors duration-200 disabled:bg-gray-300 disabled:cursor-not-allowed hover:bg-blue-600 disabled:hover:bg-gray-300"
        :disabled="isMax"
        @click="increment"
      >
        +
      </button>
    </div>
    <p class="italic text-gray-500">
      <span v-if="isMin">At minimum value</span>
      <span v-else-if="isMax">At maximum value</span>
      <span v-else>Counting...</span>
    </p>
  </div>
</template>

// examples/svelte/src/lib/components/CounterDisplay.svelte
<script lang="ts">
  interface Props {
    initialValue?: number
    min?: number
    max?: number
  }

  let { initialValue = 0, min = 0, max = 10 }: Props = $props()

  // Use $state with a default value, then sync in $effect
  let count = $state(0)

  // Sync count when initialValue changes
  $effect(() => {
    count = initialValue
  })

  let isMin = $derived(count <= min)
  let isMax = $derived(count >= max)

  function increment(): void {
    if (count + 1 <= max) {
      count++
    }
  }

  function decrement(): void {
    if (count - 1 >= min) {
      count--
    }
  }

  function reset(): void {
    count = min
  }
</script>

<div class="counter">
  <h2>Counter Example</h2>
  <p class="count-value">{count}</p>
  <div class="counter-buttons">
    <button type="button" disabled={isMin} onclick={decrement}>
      -
    </button>
    <button type="button" onclick={reset}>
      Reset
    </button>
    <button type="button" disabled={isMax} onclick={increment}>
      +
    </button>
  </div>
  <p class="counter-status">
    {#if isMin}
      <span>At minimum value</span>
    {:else if isMax}
      <span>At maximum value</span>
    {:else}
      <span>Counting...</span>
    {/if}
  </p>
</div>

<style>
  .counter {
    text-align: center;
    padding: 20px;
    border: 2px solid #ff3e00;
    border-radius: 12px;
    max-width: 300px;
    margin: 20px auto;
  }

  .count-value {
    font-size: 48px;
    font-weight: bold;
    color: #ff3e00;
  }

  .counter-buttons {
    display: flex;
    justify-content: center;
    gap: 12px;
    margin: 16px 0;
  }

  .counter-buttons button {
    padding: 12px 24px;
    font-size: 18px;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    background-color: #ff3e00;
    color: white;
    transition: background-color 0.2s;
  }

  .counter-buttons button:disabled {
    background-color: #ccc;
    cursor: not-allowed;
  }

  .counter-buttons button:hover:not(:disabled) {
    background-color: #d63500;
  }

  .counter-status {
    font-style: italic;
    color: #666;
  }
</style>
