// examples/vue3/src/components/DataTable.vue
<script setup lang="ts">
import { computed, ref, type Ref } from 'vue'

interface Column<T> {
  key: keyof T
  header: string
  sortable?: boolean
  render?: (value: T[keyof T], row: T) => string
}

interface DataTableProps<T> {
  columns: Column<T>[]
  data: T[]
  pageSize?: number
  rowKey: keyof T
}

const props = withDefaults(defineProps<DataTableProps<Record<string, unknown>>>(), {
  pageSize: 10,
})

const sortKey: Ref<string | null> = ref(null)
const sortDirection: Ref<'asc' | 'desc'> = ref('asc')
const currentPage: Ref<number> = ref(1)

const sortedData = computed(() => {
  if (!sortKey.value) return props.data

  return [...props.data].sort((a, b) => {
    const aVal = a[sortKey.value!]
    const bVal = b[sortKey.value!]

    if (aVal === bVal) return 0
    if (aVal === null || aVal === undefined) return 1
    if (bVal === null || bVal === undefined) return -1

    const comparison = aVal < bVal ? -1 : 1
    return sortDirection.value === 'asc' ? comparison : -comparison
  })
})

const paginatedData = computed(() => {
  const start = (currentPage.value - 1) * props.pageSize
  return sortedData.value.slice(start, start + props.pageSize)
})

const totalPages = computed(() => Math.ceil(props.data.length / props.pageSize))

function handleSort(key: string): void {
  if (sortKey.value === key) {
    sortDirection.value = sortDirection.value === 'asc' ? 'desc' : 'asc'
  } else {
    sortKey.value = key
    sortDirection.value = 'asc'
  }
}

function nextPage(): void {
  if (currentPage.value < totalPages.value) {
    currentPage.value++
  }
}

function prevPage(): void {
  if (currentPage.value > 1) {
    currentPage.value--
  }
}

function goToPage(page: number): void {
  if (page >= 1 && page <= totalPages.value) {
    currentPage.value = page
  }
}
</script>

<template>
  <div class="data-table">
    <table>
      <thead>
        <tr>
          <th
            v-for="column in columns"
            :key="String(column.key)"
            :class="{ sortable: column.sortable }"
            @click="column.sortable && handleSort(String(column.key))"
          >
            {{ column.header }}
            <span
              v-if="column.sortable && sortKey === column.key"
              class="sort-icon"
            >
              {{ sortDirection === 'asc' ? ' ↑' : ' ↓' }}
            </span>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="row in paginatedData"
          :key="String(row[rowKey])"
        >
          <td
            v-for="column in columns"
            :key="String(column.key)"
          >
            <template v-if="column.render">
              {{ column.render(row[column.key], row) }}
            </template>
            <template v-else>
              {{ row[column.key] }}
            </template>
          </td>
        </tr>
      </tbody>
    </table>

    <div
      v-if="totalPages > 1"
      class="pagination"
    >
      <button
        type="button"
        :disabled="currentPage === 1"
        @click="prevPage"
      >
        Previous
      </button>
      <span
        v-for="page in totalPages"
        :key="page"
        class="page-number" :class="[{ active: currentPage === page }]"
        @click="goToPage(page)"
      >
        {{ page }}
      </span>
      <button
        type="button"
        :disabled="currentPage === totalPages"
        @click="nextPage"
      >
        Next
      </button>
    </div>
  </div>
</template>

<style scoped>
.data-table {
  width: 100%;
}

table {
  border-collapse: collapse;
  width: 100%;
}

th {
  border-bottom: 2px solid #ddd;
  padding: 12px;
  text-align: left;
}

th.sortable {
  cursor: pointer;
  user-select: none;
}

th.sortable:hover {
  background-color: #f5f5f5;
}

td {
  border-bottom: 1px solid #ddd;
  padding: 12px;
}

.pagination {
  display: flex;
  gap: 8px;
  justify-content: center;
  margin-top: 16px;
}

.page-number {
  cursor: pointer;
  padding: 4px 8px;
}

.page-number.active {
  background-color: #42b883;
  border-radius: 4px;
  color: white;
}

button:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}
</style>

// examples/svelte/src/lib/components/DataTable.svelte
<script lang="ts" generics="T extends Record<string, unknown>">
  import type { Snippet } from 'svelte'

  interface Column {
    key: keyof T
    header: string
    sortable?: boolean
    render?: (value: T[keyof T], row: T) => string
  }

  interface DataTableProps {
    columns: Column[]
    data: T[]
    pageSize?: number
    rowKey: keyof T
    children?: Snippet<{ row: T; column: Column; value: T[keyof T] }>
  }

  let { columns, data, pageSize = 10, rowKey, children }: DataTableProps = $props()

  let sortKey = $state<string | null>(null)
  let sortDirection = $state<'asc' | 'desc'>('asc')
  let currentPage = $state(1)

  let sortedData = $derived(() => {
    if (!sortKey) return data

    return [...data].sort((a, b) => {
      const aVal = a[sortKey!]
      const bVal = b[sortKey!]

      if (aVal === bVal) return 0
      if (aVal === null || aVal === undefined) return 1
      if (bVal === null || bVal === undefined) return -1

      const comparison = aVal < bVal ? -1 : 1
      return sortDirection === 'asc' ? comparison : -comparison
    })
  })

  let paginatedData = $derived(() => {
    const start = (currentPage - 1) * pageSize
    return sortedData().slice(start, start + pageSize)
  })

  let totalPages = $derived(Math.ceil(data.length / pageSize))

  function handleSort(key: string): void {
    if (sortKey === key) {
      sortDirection = sortDirection === 'asc' ? 'desc' : 'asc'
    } else {
      sortKey = key
      sortDirection = 'asc'
    }
  }

  function nextPage(): void {
    if (currentPage < totalPages) {
      currentPage++
    }
  }

  function prevPage(): void {
    if (currentPage > 1) {
      currentPage--
    }
  }

  function goToPage(page: number): void {
    if (page >= 1 && page <= totalPages) {
      currentPage = page
    }
  }
</script>

<div class="data-table">
  <table>
    <thead>
      <tr>
        {#each columns as column (column.key)}
          <th
            class:sortable={column.sortable}
            onclick={() => column.sortable && handleSort(String(column.key))}
          >
            {column.header}
            {#if column.sortable && sortKey === column.key}
              <span class="sort-icon">
                {sortDirection === 'asc' ? ' ↑' : ' ↓'}
              </span>
            {/if}
          </th>
        {/each}
      </tr>
    </thead>
    <tbody>
      {#each paginatedData() as row (String(row[rowKey]))}
        <tr>
          {#each columns as column (column.key)}
            <td>
              {#if children}
                {@render children({ row, column, value: row[column.key] })}
              {:else if column.render}
                {column.render(row[column.key], row)}
              {:else}
                {String(row[column.key] ?? '')}
              {/if}
            </td>
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>

  {#if totalPages > 1}
    <div class="pagination">
      <button
        type="button"
        disabled={currentPage === 1}
        onclick={prevPage}
      >
        Previous
      </button>
      {#each Array.from({ length: totalPages }, (_, i) => i + 1) as page (page)}
        <button
          type="button"
          class="page-number"
          class:active={currentPage === page}
          onclick={() => goToPage(page)}
        >
          {page}
        </button>
      {/each}
      <button
        type="button"
        disabled={currentPage === totalPages}
        onclick={nextPage}
      >
        Next
      </button>
    </div>
  {/if}
</div>

<style>
  .data-table {
    width: 100%;
  }

  table {
    border-collapse: collapse;
    width: 100%;
  }

  th {
    border-bottom: 2px solid #ddd;
    padding: 12px;
    text-align: left;
  }

  th.sortable {
    cursor: pointer;
    user-select: none;
  }

  th.sortable:hover {
    background-color: #f5f5f5;
  }

  td {
    border-bottom: 1px solid #ddd;
    padding: 12px;
  }

  .pagination {
    display: flex;
    gap: 8px;
    justify-content: center;
    margin-top: 16px;
  }

  .page-number {
    cursor: pointer;
    padding: 4px 8px;
  }

  .page-number.active {
    background-color: #42b883;
    border-radius: 4px;
    color: white;
  }

  button:disabled {
    cursor: not-allowed;
    opacity: 0.5;
  }
</style>
