// examples/vue2/src/components/UserCard.vue
<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'UserCard',
  props: {
    user: {
      type: Object as () => {
        email: string
        id: number
        name: string
        role: 'admin' | 'user' | 'guest'
      },
      required: true,
    },
    showEmail: {
      type: Boolean,
      default: false,
    },
  },
  computed: {
    displayName(): string {
      return this.user.name.toUpperCase()
    },
    roleClass(): string {
      return `badge-${this.user.role}`
    },
  },
  methods: {
    handleSelect(): void {
      this.$emit('select', this.user)
    },
    handleDelete(): void {
      this.$emit('delete', this.user.id)
    },
  },
})
</script>

<template>
  <div class="user-card">
    <div class="user-header">
      <span class="user-name">
        {{ displayName }}
      </span>
      <span class="role-badge" :class="[roleClass]">
        {{ user.role }}
      </span>
    </div>
    <p
      v-if="showEmail"
      class="user-email"
    >
      {{ user.email }}
    </p>
    <div class="user-actions">
      <button
        type="button"
        class="btn-select"
        @click="handleSelect"
      >
        Select
      </button>
      <button
        type="button"
        class="btn-delete"
        @click="handleDelete"
      >
        Delete
      </button>
    </div>
  </div>
</template>

<style scoped>
.user-card {
  border: 1px solid #ddd;
  border-radius: 8px;
  padding: 16px;
  margin: 8px;
  min-width: 200px;
}

.user-header {
  align-items: center;
  display: flex;
  justify-content: space-between;
  margin-bottom: 8px;
}

.user-name {
  font-weight: bold;
}

.role-badge {
  border-radius: 4px;
  font-size: 12px;
  padding: 2px 8px;
}

.badge-admin {
  background-color: #ff4d4f;
  color: white;
}

.badge-user {
  background-color: #1890ff;
  color: white;
}

.badge-guest {
  background-color: #d9d9d9;
  color: #333;
}

.user-email {
  color: #666;
  font-size: 14px;
  margin-bottom: 12px;
}

.user-actions {
  display: flex;
  gap: 8px;
}

.user-actions button {
  flex: 1;
  padding: 8px 12px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.btn-select {
  background-color: #42b883;
  color: white;
}

.btn-delete {
  background-color: #ff4d4f;
  color: white;
}
</style>

// examples/svelte/src/lib/components/UserCard.svelte
<script lang="ts">
  import type { User } from '../utils/helpers'

  interface Props {
    user: User
    showEmail?: boolean
    onselect?: (user: User) => void
    ondelete?: (userId: number) => void
  }

  let { user, showEmail = false, onselect, ondelete }: Props = $props()

  let displayName = $derived(user.name.toUpperCase())
  let roleBadgeClass = $derived(`badge-${user.role}`)

  function handleSelect(): void {
    onselect?.(user)
  }

  function handleDelete(): void {
    ondelete?.(user.id)
  }
</script>

<div class="user-card">
  <div class="user-header">
    <span class="user-name">{displayName}</span>
    <span class="role-badge {roleBadgeClass}">{user.role}</span>
  </div>
  {#if showEmail}
    <p class="user-email">{user.email}</p>
  {/if}
  <div class="user-actions">
    <button type="button" class="btn-select" onclick={handleSelect}>
      Select
    </button>
    <button type="button" class="btn-delete" onclick={handleDelete}>
      Delete
    </button>
  </div>
</div>

<style>
  .user-card {
    border: 1px solid #ddd;
    border-radius: 8px;
    padding: 16px;
    margin-bottom: 12px;
  }

  .user-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .user-name {
    font-weight: bold;
    font-size: 18px;
  }

  .role-badge {
    padding: 4px 8px;
    border-radius: 4px;
    font-size: 12px;
    text-transform: uppercase;
  }

  .badge-admin {
    background-color: #ff4757;
    color: white;
  }

  .badge-user {
    background-color: #2ed573;
    color: white;
  }

  .badge-guest {
    background-color: #747d8c;
    color: white;
  }

  .user-email {
    color: #666;
    margin: 8px 0;
  }

  .user-actions {
    display: flex;
    gap: 8px;
    margin-top: 12px;
  }

  .btn-select,
  .btn-delete {
    padding: 8px 16px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .btn-select {
    background-color: #ff3e00;
    color: white;
  }

  .btn-delete {
    background-color: #ff4757;
    color: white;
  }
</style>
